
### MAKING NICE PLOTS. 
# So far you've been visualizing just the list of output numbers
# You can visualize all of the variables that you've created using the 'plot' function (as well as a number of more sophisticated plotting functions). 
# What do you think that each of the arguments means for the plot function?
# A cool thing about R is that the options for the arguments make sense. Try making up a different one and see if it works

plot (p_pop1, xlab="time", ylab ="p in population 1", type = "p", col = "red")


# You can also combine plots together into a single figure
par(mfrow=c(3,3))
plot (p_pop1, xlab="time", ylab ="p in population 1", type = "p", col = 'red')
plot (p_pop2, xlab="time", ylab ="p in population 2", type = "p", col = 'red')
plot (p2_pop2, xlab="time", ylab ="p2 in population 2", type = "p", col = 'red')
plot (p_pop1, xlab="time", ylab ="p in population 1", type = "l", col = 'blue')
plot (p_pop2, xlab="time", ylab ="p in population 2", type = "l", col = 'blue')
plot (p2_pop2, xlab="time", ylab ="p2 in population 2", type = "l", col = 'blue')
plot (p_pop1, xlab="time", ylab ="p in population 1", type = "b", col = 'green')
plot (p_pop2, xlab="time", ylab ="p in population 2", type = "b", col = 'green')
plot (p2_pop2, xlab="time", ylab ="p2 in population 2", type = "b", col = 'green')


# Data can be generated by being sampled from nearly any distribution

# Binomial Distribution
# function rbinom takes three parameters
#  1. The number of observations to generate
#  2. The number of trials for each observation
#  3. Probability of a success

b <- rbinom(n=100, size=20, prob=0.5)
hist(b)


# This kind of statement can be run in one line as well,

hist(rbinom(n=100, size=20, prob=0.5))


# You can even set up a vector of values that you feed into a distribution function to see the output
x <- seq(0,100,by=1)
y <- dbinom(x,100,0.6)
plot(x,y)


# Poisson Distribution
# function rpois takes two parameters
#  1. The number of observations to generate (random numbers)
#  2. The mean value of observations

r <- rpois(n=100, lambda=1)
hist(r)


# Normal Distribution
# function rnorm takes three parameters
#  1. the number of observations to return
#  2. The mean of the population
#  3. The standard deviation of the population

n <- rnorm(n=100, mean=10, sd=4)
hist(n)


# you can have more than plot in a single figure. Try the following and see what happens
Y <- rnorm(1000, 0, 10)
hist(x, xlim = c(-50,50))
curve(5000*dnorm(x, 0, 10), xlim = c(-50,50), add=TRUE)

# This exercise will help you get used to reading in and manipulating data files
# First off, remember to set your working directory to find your file correctly

Perc_Data <- read.table('Perchlorate_Data.csv', header=T, sep=',')

# OK, now let's look at the data
print (Perc_Data)

# This is a little easier
head (Perc_Data)
tail (Perc_Data)

# How do we look at a subset of the data?
# Can you see how we can do the same thing different ways?

print (Perc_Data[,2])

print (Perc_Data[1,])

print (Perc_Data[1,2])

print (Perc_Data$T4_Hormone_Level)

print (Perc_Data$T4_Hormone_Level>45.0)

# OK, let's try some summary stats and figures

blah <- summary(Perc_Data$T4_Hormone_Level)
print (blah)

hist(Perc_Data$T4_Hormone_Level)

boxplot(Perc_Data$T4_Hormone_Level)

plot(Perc_Data$T4_Hormone_Level,Perc_Data$Follicle_Area)

boxplot(Perc_Data$T4_Hormone_Level~Perc_Data$Perchlorate_Level, col = "red", notch = T, ylab = "T4 Hormone level", xlab = "Treatment level", border ="orange", main = "Boxplot of variation in T4 levels of zebrafish across different treatments of perchlorate")


