---
title: "Covid-19 graphs"
author: "Hannah Tavalire"
date: "3/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(reshape)
```

```{r covid graph}
d <- read.csv("time_series_19-covid-Confirmed.csv", header=T, check.names=F)

cols <- as.character(colnames(d[,5:length(d)]))
ds <- melt(d,id.vars = c("Province/State","Country/Region"), measure.vars = cols)
colnames(ds) <- c("Province_State","Country_Region","Date","Case_Count")

str(ds)
dss <- subset(ds, ds$Province_State!="")
head(dss)
str(dss)


ggplot() +
  geom_line(aes(x=Date, y=Case_Count, group=Province_State, color=Country_Region), data=dss)+
  theme(text = element_text(family="Helvetica",size=8, face="plain"),
        strip.text.y = element_text(angle = 0, size=8, face="bold"),
        strip.background = element_blank(),
        axis.line.x = element_line(color="black", size = 0.25),
        axis.line.y = element_line(color="black", size = 0.25),
        axis.text.y=element_text(color="black", size=4.5),
        axis.text.x=element_text(color="black", size=8,angle = 90),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(vjust=2),
        axis.title.y = element_text(vjust =0))


#look at what's going on outside of Wuhan
ggplot() +
  geom_line(aes(x=Date, y=Case_Count, group=Province_State, color=Country_Region), data=dss)+
  ylim(0,2000)+
  theme(text = element_text(family="Helvetica",size=8, face="plain"),
        strip.text.y = element_text(angle = 0, size=8, face="bold"),
        strip.background = element_blank(),
        axis.line.x = element_line(color="black", size = 0.25),
        axis.line.y = element_line(color="black", size = 0.25),
        axis.text.y=element_text(color="black", size=4.5),
        axis.text.x=element_text(color="black", size=8,angle = 90),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(vjust=2),
        axis.title.y = element_text(vjust =0))
```
