---
title: "Design of Experiments, and Analysis of Variance"
author: "Peter Ralph"
date: "8 October -- Advanced Biological Statistics"
---

```{r setup, include=FALSE}
fig.dim <- 4
knitr::opts_chunk$set(fig.width=2*fig.dim,
                      fig.height=fig.dim,
                      fig.align='center')
set.seed(23)
library(tidyverse)
library(rstan)
library(matrixStats)
options(mc.cores = parallel::detectCores())
```

# Outline

## Goal for the week

To compare means of some measurement between groups.

. . .

Using statistics.

. . .

- When can you do it, and how well? Power/sensitivity, false positive rate.
- How can experiments best do it? Experimental design.
- Methods: two-sample $t$-test, (one-way) ANOVA, permutation tests

# Means of two groups

## 30 min

- introduce the idea
- apply to simple example // group discussion: interpret `t.test` output
- plot data, notice outlier
- alternative: do permutation test (demo in R?)


# Power and false positives

## 35 min

- definitions: depends on the model!
- group discussion: examples when each are high, low
- demo: obtain power for two-sample $t$ by simulation
- group ex: same for false pos

# Experimental design

## 40 min

- effect size: rules of thumb for detectable/not
- confounding factors
- representative samplesj
- how to ask: what will we *actually* measure/test?
- tools: replication, independence, controls, randomization, pairs
- group exercise: design an experiment to do X - identify confounders, deal with them

<!-- THURSDAY -->

# Tidy data

## 20 min

- rectangular, semantic
- wide vs long
- metadata!
- group ex: design data format for experiment

# ANOVA

## 50 min

- goal
- example and visualization
- on-board disc of power, sens
- analyze example
- testing assumptions
- demo: verify by simulation properties when asummptions hold (maybe unequal variance?)
- group ex: see what happens when they don't


# Permutation tests

## 30 min

- definition
- demo: do it by defining a function
- group discussion: figure out how to do it in some examples



