---
title: "the Weibull distribution"
author: "Peter Ralph"
date: "5 January 2021 -- Advanced Biological Statistics"
---


```{r setup, include=FALSE}
fig.dim <- 4
knitr::opts_chunk$set(fig.width=2*fig.dim,
                      fig.height=fig.dim,
                      fig.align='center',
                      warning=FALSE)
set.seed(42)
library(survival)
library(matrixStats)
options(mc.cores = parallel::detectCores())
```



# Stochastic minute: Weibull

## The Weibull distribution

If $T$ has a [Weibull distribution](https://en.wikipedia.org/wiki/Weibull_distribution),
with scale $\lambda$ and shape $k$,
then

- $T \ge 0$
- $\P\{ T > t \} = \exp\left(- (t/\lambda)^k \right)$
- the mean is proportional to the scale:
  $\E[T] = \lambda \times \Gamma(1 + 1/k)$

. . .

It is mostly used in survival analysis,
because its *hazard rate* is:
$$\begin{aligned}
    h(t) = k \frac{1}{\lambda} \left(\frac{t}{\lambda}\right)^{k-1} .
\end{aligned}$$
which allows rates to go down ($k<1$), up ($k>1$), or stay constant ($k=1$) over time.

##

```{r plot_wei, fig.height=2*fig.dim, fig.width=3*fig.dim, echo=FALSE}
kvals <- c(0.5, 0.75, 1, 1.5, 2)
xx <- seq(0, 1.5, length.out=101)
x <- sapply(kvals, function (k) dweibull(xx, shape=k)/pweibull(xx, shape=k, lower.tail=FALSE))
matplot(xx, x, type='l', lty=1, xlab='time', ylab='hazard rate', lwd=2)
legend("top", lty=1, col=1:5, legend=sprintf("shape=%0.2f", kvals))
```

